<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LFR011478" name="Test.NewTest_ZAP" tests="3" failures="0" timestamp="17 Aug 2016 13:24:11 GMT" time="12.864" errors="1">
  <testcase name="generationReport" time="1.030" classname="Test.NewTest_ZAP">
    <error type="br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApiException" message="java.lang.NullPointerException">
      <![CDATA[br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApiException: java.lang.NullPointerException
	at br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApi.callApiOther(ClientApi.java:324)
	at br.com.softplan.security.zap.zaproxy.clientapi.gen.Core.xmlreport(Core.java:547)
	at configZAP.Zap.GeneratingReport(Unknown Source)
	at Test.NewTest_ZAP.generationReport(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.TestNG.privateMain(TestNG.java:1355)
	at org.testng.TestNG.main(TestNG.java:1324)
Caused by: java.lang.NullPointerException
	at br.com.softplan.security.zap.zaproxy.clientapi.core.ClientApi.callApiOther(ClientApi.java:319)
	... 26 more
]]>
    </error>
  </testcase> <!-- generationReport -->
  <testcase name="lancementSelenium" time="11.822" classname="Test.NewTest_ZAP"/>
  <testcase name="demarrageZap" time="0.012" classname="Test.NewTest_ZAP"/>
</testsuite> <!-- Test.NewTest_ZAP -->
